### ISSUE TITLE
Does not work in Mac os Yosemite, got `Killed: 9`

### ISSUE THREAD

**Issue by justbilt** [m3ng9i/qreader#1]
got `Killed: 9` on Mac OS when input `./qreader_darwin_amd64 init`
## solution:

```
brew install upx
upx -d qreader_darwin_amd64
```

**Comment by m3ng9i** [comment]
Thanks for the feedback.

I built `qreader_darwin_amd64` on Mac OS X Mavericks and use UPX to make it smaller. Maybe it's not compatible with other version of OS X.

I just replaced the binary `qreader_darwin_amd64` with one not packed with UPX in [v0.2 release](https://github.com/m3ng9i/qreader/releases/tag/v0.2).
