### ISSUE TITLE
关于自定义feed更新频率

### ISSUE THREAD

**Issue by kkkpc** [m3ng9i/qreader#2]
作者你好，没有看到config.ini自定义feed更新的时间频率的设定？
程序默认是多久去取一次feed啊？

**Comment by m3ng9i** [comment]
默认更新时间是 120 分钟（两个小时），写死到代码里了。在 qreader.go 中：

``` go
    model.AutoUpdateFeed(120)
```

如果要修改默认的更新时间，需要自己改代码，然后编译。如果要修改某个 feed 的更新时间，在 qreader 的订阅界面， 找到要修改的 feed，点击“详”按钮，在“更新周期（分钟）”框后面，输入你要设置的分钟数即可。

**Comment by kkkpc** [comment]
好的谢谢
